version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: scaffold-api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env 
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./webpack.config.js:/app/webpack.config.js
      - ./tsconfig.json:/app/tsconfig.json